server:
  port: 8088
# 配置异构服务
sidecar:
  ip: ${IP:localhost}
  port: ${PORT:8089}
  health-check-url: ${HEALTH_CHECK_URL:http://${sidecar.ip}:${sidecar.port}/health}
spring:
  application:
    name: ${APPLICATION_NAME:micro-sidecar}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:http://localhost}:${NACOS_PORT:38848}
        #        拓展标签信息
        metadata:
          author: ${AUTHOR:}
          version: ${VERSION:1.0}
        namespace: ${ACTIVE_ENV:dev}
    gateway:
      routes:
        - id: main-route
          uri: http://${sidecar.ip}:${sidecar.port}
          predicates:
            - Header=XXX-Origin, .*
      discovery:
        locator:
          enabled: true